name: pavimenta_ia
description: MVP Android de dashcam para detecção local de buracos.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  geolocator: 14.1.1
  path_provider: 2.1.5
  permission_handler: 13.0.2
  ultralytics_yolo: 0.6.15
  wakelock_plus: 1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
